//for authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

//for users
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const EDIT_USER_START = 'EDIT_USER_START';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// for assign users
export const GET_PROJECT_USER_START = 'GET_PROJECT_USERS_START';
export const GET_PROJECT_USER_SUCCESS = 'GET_PROJECT_USER_SUCCESS';
export const GET_PROJECT_USER_FAIL = 'GET_PROJECT_USER_FAIL';

export const ADD_PROJECT_USER_START = 'ADD_PROJECT_USER_START';
export const ADD_PROJECT_USER_SUCCESS = 'ADD_PROJECT_USER_SUCCESS';
export const ADD_PROJECT_USER_FAIL = 'ADD_PROJECT_USER_FAIL';

export const REMOVE_PROJECT_USER_START = 'REMOVE_PROJECT_USER_START';
export const REMOVE_PROJECT_USER_SUCCESS = 'REMOVE_PROJECT_USER_SUCCESS';
export const REMOVE_PROJECT_USER_FAIL = 'REMOVE_PROJECT_USER_FAIL';

export const SET_PROJECT_USER = 'SET_PROJECT_USER';
